# Generated by Django 4.2.7 on 2023-11-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_delete_adress_rename_telefone_client_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="cpf",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(max_length=14),
        ),
    ]
